/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;

/**
 *
 * @author Javir
 */
public class PanelAltasAnalista extends javax.swing.JPanel {
    Lista listado;
    
    
    public PanelAltasAnalista() {
      
        initComponents();
        //MensajeError.setName("ERROR DNI");
        MensajeError.setVisible(false);
        
    }
    
    public void pedirFoco(){
        nombreField.requestFocus();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        sueldoLabel = new javax.swing.JLabel();
        sueldoField = new javax.swing.JTextField();
        EdadLabel = new javax.swing.JLabel();
        EdadField = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        DniField = new javax.swing.JTextField();
        DniLabel = new javax.swing.JLabel();
        MensajeError = new javax.swing.JOptionPane();
        fechaLabel = new javax.swing.JLabel();
        fechaField3 = new javax.swing.JTextField();
        fechaField2 = new javax.swing.JTextField();
        fechaField1 = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        nombreLabel.setText("Nombre: ");

        nombreField.setToolTipText("");
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        sueldoLabel.setText("Sueldo: ");

        sueldoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoFieldActionPerformed(evt);
            }
        });

        EdadLabel.setText("Edad: ");

        EdadField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadFieldActionPerformed(evt);
            }
        });

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        DniField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniFieldActionPerformed(evt);
            }
        });

        DniLabel.setText("DNI: ");

        MensajeError.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                MensajeErrorComponentShown(evt);
            }
        });

        fechaLabel.setText("Fecha de contratación (dd/mm/aaaa): ");

        fechaField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaField3ActionPerformed(evt);
            }
        });

        fechaField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaField2ActionPerformed(evt);
            }
        });

        fechaField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sueldoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EdadLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DniLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EdadField)
                            .addComponent(DniField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sueldoField)
                            .addComponent(nombreField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btAceptar)
                .addGap(297, 297, 297))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniLabel)
                    .addComponent(DniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EdadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EdadLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btAceptar)
                .addGap(65, 65, 65)
                .addComponent(MensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        
        Object ob=new Object();
        
        
        if(Empleado.comprobarSueldo(Float.parseFloat(sueldoField.getText())) && 
                Analista.comprobarDni(DniField.getText()) && 
                Analista.comprobarEdad(Integer.parseInt(EdadField.getText())) ){
            
            MensajeError.setVisible(false);
            
            ob=new Analista(nombreField.getText(),Float.parseFloat(sueldoField.getText()),Integer.parseInt(fechaField1.getText())
                    ,Integer.parseInt(fechaField2.getText()),Integer.parseInt(fechaField3.getText())
                    ,Integer.parseInt(EdadField.getText()),DniField.getText());
            
            listado.insertar(ob);
            
        }else if(!Analista.comprobarDni(DniField.getText())){
            
            setMensajeError("Dni incorrecto, inténtelo de nuevo.");
        }else if(!Empleado.comprobarSueldo(Float.parseFloat(sueldoField.getText()))){
            setMensajeError("Sueldo incorrecto, supera el sueldo máximo establecido ("+Empleado.getSueldoMax()+") o es inferior al mínimo (1000), inténtelo de nuevo.");
        }else if(!Analista.comprobarEdad(Integer.parseInt(EdadField.getText())))
            setMensajeError("Edad incorrecta, es menor de edad o supera los 75 años, inténtelo de nuevo");
        
        setFieldNull();
        
    }//GEN-LAST:event_btAceptarActionPerformed

    private void setFieldNull(){
       
        nombreField.setText(null);
        EdadField.setText(null);
        DniField.setText(null);
        sueldoField.setText(null);
        fechaField1.setText(null);
        fechaField2.setText(null);
        fechaField3.setText(null);
        nombreField.requestFocus();
    }
    
    private void setMensajeError(String mensaje){
        MensajeError.setMessage(mensaje);
        MensajeError.setVisible(true);
    }
    
    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void DniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniFieldActionPerformed

    private void sueldoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoFieldActionPerformed

    private void MensajeErrorComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MensajeErrorComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MensajeErrorComponentShown

    private void fechaField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaField3ActionPerformed

    private void fechaField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaField2ActionPerformed

    private void fechaField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaField1ActionPerformed

    private void EdadFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadFieldActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DniField;
    private javax.swing.JLabel DniLabel;
    private javax.swing.JTextField EdadField;
    private javax.swing.JLabel EdadLabel;
    private javax.swing.JOptionPane MensajeError;
    private javax.swing.JButton btAceptar;
    private javax.swing.JTextField fechaField1;
    private javax.swing.JTextField fechaField2;
    private javax.swing.JTextField fechaField3;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField sueldoField;
    private javax.swing.JLabel sueldoLabel;
    // End of variables declaration//GEN-END:variables
}
