/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Javir
 */
public class PanelAltasAnalista extends javax.swing.JPanel {
    Lista listado;
    
    
    public PanelAltasAnalista() {
      
        initComponents();
        
    }
    
    public void pedirFoco(){
        nombreField.requestFocus();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        sueldoLabel = new javax.swing.JLabel();
        sueldoField = new javax.swing.JTextField();
        PlusLabel = new javax.swing.JLabel();
        PlusField = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();
        DniField = new javax.swing.JTextField();
        DniLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        sueldoMaxLabel = new javax.swing.JLabel();
        sueldoMaxField = new javax.swing.JTextField();
        IdLabel = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        nombreLabel.setText("Nombre: ");

        nombreField.setToolTipText("");
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        sueldoLabel.setText("Sueldo: ");

        sueldoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoFieldActionPerformed(evt);
            }
        });

        PlusLabel.setText("Plus:");

        PlusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusFieldActionPerformed(evt);
            }
        });

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        DniField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DniFieldActionPerformed(evt);
            }
        });

        DniLabel.setText("DNI: ");

        fechaLabel.setText("Fecha de contratación (dd/mm/aaaa): ");

        fechaField.setText("dd/mm/aaaa");
        fechaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaFieldActionPerformed(evt);
            }
        });

        sueldoMaxLabel.setText("Sueldo Máximo: ");

        sueldoMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoMaxFieldActionPerformed(evt);
            }
        });

        IdLabel.setText("ID:");

        IdField.setToolTipText("");
        IdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sueldoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PlusLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DniLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sueldoMaxLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IdLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PlusField)
                                    .addComponent(DniField)
                                    .addComponent(sueldoField)
                                    .addComponent(nombreField)
                                    .addComponent(sueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAceptar)
                        .addGap(224, 224, 224)))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DniLabel)
                    .addComponent(DniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlusLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sueldoMaxLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btAceptar)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        
        Analista ob=null;
        
        String[] fecha=fechaField.getText().split("/");//[0]=dia [1]=mes [2]=año
        
        if(ob.comprobarSueldo(Float.parseFloat(sueldoField.getText())) && 
                Analista.comprobarDni(DniField.getText()) && 
               Empleado.comprobarId(Integer.parseInt(PlusField.getText())) ){
            
            
            
            ob=new Analista(Integer.parseInt(IdField.getText()),nombreField.getText(),Float.parseFloat(sueldoField.getText()),Float.parseFloat(sueldoMaxField.getText())
                    ,Integer.parseInt( fecha[2]),Integer.parseInt( fecha[2]),Integer.parseInt( fecha[2]),Float.parseFloat(PlusField.getText()),DniField.getText());
            
            listado.insertar(ob);
            
        }else if(!Analista.comprobarDni(DniField.getText())){
            
            setMensajeError("Dni incorrecto, inténtelo de nuevo.");
        }else if(!ob.comprobarSueldo(Float.parseFloat(sueldoField.getText()))){
            setMensajeError("Sueldo incorrecto, supera el sueldo máximo establecido ("+ob.getSueldoMax()+") o es inferior al mínimo (1000), inténtelo de nuevo.");
        }else if(!ob.comprobarPlus(Float.parseFloat(PlusField.getText())))
            setMensajeError("Plus incorrecto, es menor de 0% o supera el 100%, inténtelo de nuevo");
        
        setFieldNull();
        
    }//GEN-LAST:event_btAceptarActionPerformed

    private void setFieldNull(){
       
        nombreField.setText(null);
        PlusField.setText(null);
        DniField.setText(null);
        sueldoField.setText(null);
        sueldoMaxField.setText(null);
        fechaField.setText(null);
        nombreField.requestFocus();
    }
    
    private void setMensajeError(String mensaje){
        JOptionPane.showMessageDialog(this,mensaje,"Error en la introducción de datos",JOptionPane.WARNING_MESSAGE);
    }
    
    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void DniFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DniFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DniFieldActionPerformed

    private void sueldoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoFieldActionPerformed

    private void fechaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaFieldActionPerformed
        // TODO add your handling code here:
        
        if(fechaField.isFocusOwner())
            fechaField.setText(null);
        
    }//GEN-LAST:event_fechaFieldActionPerformed

    private void PlusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusFieldActionPerformed

    private void sueldoMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoMaxFieldActionPerformed

    private void IdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFieldActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DniField;
    private javax.swing.JLabel DniLabel;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField PlusField;
    private javax.swing.JLabel PlusLabel;
    private javax.swing.JButton btAceptar;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField sueldoField;
    private javax.swing.JLabel sueldoLabel;
    private javax.swing.JTextField sueldoMaxField;
    private javax.swing.JLabel sueldoMaxLabel;
    // End of variables declaration//GEN-END:variables
}
