/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Lista;
import Controlador.Nodo;
import Modelo.Empleado;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Javir
 */
public class PanelOrdenar extends javax.swing.JPanel {

    Lista listado;
    ArrayList<Empleado> empleados=new ArrayList<Empleado>();
    DefaultListModel lista= new DefaultListModel();
    
    public PanelOrdenar() {
        initComponents();
        jList.setModel(lista);
    }
    
    public void rellenarArray(){
        
        empleados.clear();
        
        Nodo aux=listado.getInicio();
        
           while(aux!=null){
               empleados.add((Empleado)aux.getDato());
               aux=aux.getSiguiente();
           }
    }
    
    
    public void vaciarLista(){
       lista.removeAllElements();
   }
    
    private void ordenarLista() {
        Empleado aux;
        
        for (int i = 0; i < empleados.size()-1; i++) {
            
            for (int j =0 ; j< empleados.size()-i-1; j++) {
                if(((Empleado)empleados.get(j+1)).getId()<((Empleado)empleados.get(j)).getId()){
                    
                    aux=empleados.get(j+1);
                    
                    empleados.set(j+1, empleados.get(j));
                    empleados.set(j,aux);
                }
                    
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btOrdenarMostrar = new javax.swing.JButton();

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        btOrdenarMostrar.setText("Ordenar y mostrar");
        btOrdenarMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btOrdenarMostrar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btOrdenarMostrar)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btOrdenarMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarMostrarActionPerformed
        
        lista.removeAllElements();
        
        ordenarLista();
        
        for (int i = 0; i < empleados.size(); i++) {
            
            lista.addElement(empleados.get(i));
            
        }
    }//GEN-LAST:event_btOrdenarMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOrdenarMostrar;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
