/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.*;
import Modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Javir
 */
public class PanelAltasProg extends javax.swing.JPanel {
    
    Lista listado;
   
    public PanelAltasProg(Lista listado) {
        initComponents();
       
        
    }
    
    public void pedirFoco(){
        idField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        sueldoLabel = new javax.swing.JLabel();
        sueldoField = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        sueldoMaxField = new javax.swing.JTextField();
        sueldoMaxLabel = new javax.swing.JLabel();
        horasExtrasLabel = new javax.swing.JLabel();
        fechaField = new javax.swing.JTextField();
        horasExtrasField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        sueldoExtraLabel = new javax.swing.JLabel();
        sueldoExtraField = new javax.swing.JTextField();

        nombreLabel.setText("Nombre: ");

        nombreField.setToolTipText("");
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        sueldoLabel.setText("Sueldo: ");

        sueldoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoFieldActionPerformed(evt);
            }
        });

        fechaLabel.setText("Fecha de contratación (dd/mm/aaaa):");

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        sueldoMaxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sueldoMaxFieldActionPerformed(evt);
            }
        });

        sueldoMaxLabel.setText("Sueldo Máximo:");

        horasExtrasLabel.setText("Horas Extras:");

        horasExtrasField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horasExtrasFieldActionPerformed(evt);
            }
        });

        idLabel.setText("Id:");

        idField.setToolTipText("");
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        sueldoExtraLabel.setText("Sueldo Extra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAceptar)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreLabel)
                    .addComponent(horasExtrasLabel)
                    .addComponent(idLabel)
                    .addComponent(sueldoLabel)
                    .addComponent(fechaLabel)
                    .addComponent(sueldoMaxLabel)
                    .addComponent(sueldoExtraLabel))
                .addGap(292, 292, 292)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sueldoMaxField)
                    .addComponent(fechaField)
                    .addComponent(sueldoField)
                    .addComponent(nombreField)
                    .addComponent(idField)
                    .addComponent(horasExtrasField)
                    .addComponent(sueldoExtraField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoLabel)
                    .addComponent(sueldoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoMaxLabel)
                    .addComponent(sueldoMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horasExtrasLabel)
                    .addComponent(horasExtrasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sueldoExtraLabel)
                    .addComponent(sueldoExtraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLabel)
                    .addComponent(fechaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btAceptar)
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        
        Programador ob=new Programador();
        
        String[] fecha=fechaField.getText().split("/");//[0]=dia [1]=mes [2]=año
        
        if(Empleado.comprobarSueldo(Float.parseFloat(sueldoField.getText()),Float.parseFloat(sueldoMaxField.getText())) && 
                Programador.comprobarHorasExtras(Integer.parseInt(horasExtrasField.getText())) && 
               Empleado.comprobarId(Integer.parseInt(idField.getText())) &&
                Programador.comprobarSueldoExtra(Float.parseFloat(sueldoField.getText()),
                        Float.parseFloat(sueldoMaxField.getText()),Float.parseFloat(sueldoExtraField.getText())) ){
            
            ob=new Programador(Integer.parseInt(idField.getText()),nombreField.getText(),Float.parseFloat(sueldoField.getText()),
                    Float.parseFloat(sueldoMaxField.getText())
                    ,Integer.parseInt( fecha[2]),Integer.parseInt( fecha[1]),Integer.parseInt( fecha[0]),
                    Float.parseFloat(sueldoExtraField.getText()),Integer.parseInt(horasExtrasField.getText()));
            
            listado.insertar(ob);
            
        }else if(!Programador.comprobarHorasExtras(Integer.parseInt(horasExtrasField.getText()))){
            setMensajeError("Horas extras incorrectas\nNo puede ser menor de 0, inténtelo de nuevo.");
            
        }else if(!Empleado.comprobarSueldo(Float.parseFloat(sueldoField.getText()),Float.parseFloat(sueldoMaxField.getText()))){
            setMensajeError("Sueldo incorrecto\nSupera el sueldo máximo establecido ("+((Programador)ob).getSueldoMax()+") "
                    + "o es inferior al mínimo (1000), inténtelo de nuevo.");
            
        }else if(!Programador.comprobarSueldoExtra(Float.parseFloat(sueldoField.getText()),
                        Float.parseFloat(sueldoMaxField.getText()),Float.parseFloat(sueldoExtraField.getText())))
            setMensajeError("Sueldo extra incorrecto\nEs menor de 0 o supera el sueldo máximo, inténtelo de nuevo");
        
        else if(!Empleado.comprobarId(Integer.parseInt(idField.getText())))
            setMensajeError("Id incorrecto\nEs menor de 0 o supera el 100, inténtelo de nuevo");
        
        setFieldNull();
    }//GEN-LAST:event_btAceptarActionPerformed

     private void setMensajeError(String mensaje){
        
         JOptionPane.showMessageDialog(this,mensaje,"Error en la introducción de datos",JOptionPane.ERROR_MESSAGE);
       
    }
    
    private void setFieldNull(){
       
        nombreField.setText(null);
        sueldoMaxField.setText(null);
        fechaField.setText(null);
        idField.setText(null);
        sueldoExtraField.setText(null);
        horasExtrasField.setText(null);
        sueldoField.setText(null);
        idField.requestFocus();
    }
    
    private void sueldoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoFieldActionPerformed

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void sueldoMaxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sueldoMaxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sueldoMaxFieldActionPerformed

    private void horasExtrasFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horasExtrasFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horasExtrasFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JTextField fechaField;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField horasExtrasField;
    private javax.swing.JLabel horasExtrasLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField sueldoExtraField;
    private javax.swing.JLabel sueldoExtraLabel;
    private javax.swing.JTextField sueldoField;
    private javax.swing.JLabel sueldoLabel;
    private javax.swing.JTextField sueldoMaxField;
    private javax.swing.JLabel sueldoMaxLabel;
    // End of variables declaration//GEN-END:variables
}
